fix: `npm run build` errors
This change seems to resolve the following errors in CI.

```
Run npm run build
  npm run build
  shell: /usr/bin/bash -e {0}

> tide@1.0.0 build
> npm run build:style && react-scripts build

> tide@1.0.0 build:style
> tailwindcss build src/styles.css -o src/build.css

[deprecation] Running tailwindcss without -i, please provide an input file.

Done in 8000ms.
Creating an optimized production build...
Failed to compile.

[eslint]
src/components/Button.tsx
  Line 3:11:  'Props' is not defined     no-undef
  Line 4:3:   'children' is not defined  no-undef

src/components/Description.tsx
  Line 3:11:  'Props' is not defined    no-undef
  Line 4:3:   'content' is not defined  no-undef
  Line 4:14:  '__html' is not defined   no-undef

src/components/Input.tsx
  Line 4:11:  'Props' is not defined  no-undef
  Line 5:3:   'icon' is not defined   no-undef

src/components/ModalPrompt.tsx
  Line 6:11:  'Props' is not defined           no-undef
  Line 7:3:   'title' is not defined           no-undef
  Line 8:3:   'isOpen' is not defined          no-undef
  Line 9:3:   'confirmMessage' is not defined  no-undef
  Line 10:3:  'denyMessage' is not defined     no-undef
  Line 11:3:  'longMessage' is not defined     no-undef
  Line 12:3:  'onClose' is not defined         no-undef
  Line 13:3:  'onRequestClose' is not defined  no-undef
  Line 14:3:  'onConfirm' is not defined       no-undef

src/components/Paginate.tsx
  Line 2:11:   'JSX' is defined but never used  no-unused-vars
  Line 10:11:  'PaginateProps' is not defined   no-undef
  Line 11:3:   'children' is not defined        no-undef
  Line 12:3:   'limit' is not defined           no-undef
  Line 13:3:   'onPageClick' is not defined     no-undef
  Line 13:17:  'page' is not defined            no-undef
  Line 14:3:   'page' is not defined            no-undef
  Line 15:3:   'totalResults' is not defined    no-undef

Search for the keywords to learn more about each error.

Error: Process completed with exit code 1.
```